version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: son_financas
      MYSQL_USER: financas
      MYSQL_PASSWORD: financas
    ports:
      - "3306:3306"

volumes:
  db_data: